[package]
name = "snake-bevy"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.15.3"
bevy_prng = { version = "0.9.0", features = ["wyrand"] }
bevy_rand = { version = "0.9.0" }
rand_core = "0.6.4"
